"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

APP = ['gamepython setup.py py2app -A.py']

from setuptools import setup

APP = ['game.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
