plural_noun = input(str("Plural Noun > "))
noun1 = input(str("Noun > "))
noun2 = input(str("Noun > "))
song = input(str("Song > "))
verb = input(str("Verb > "))

print("Learning to drive it a tricky process. There are a few rules you must follow.\n")
print(f"1. Keep two {plural_noun} on the steering wheel at all times.\n")
print(f"2. Stop on the {noun1} to speed up and the {noun2} to slow down.\n")
print(f"3. Your parents will just LOVE it if you play {song} on the radio.\n")
print(f"4. Make sure to honk your horn when you see {verb} on a street sign.\n")