"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Aeroblaster.py']
DATA_FILES = ["/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/font/large_font.png",
 "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/font/small_font.png",
  "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/core/idle/idle_1.png",
   "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/core/idle/idle_0.png",
    "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/fall/fall_0.png",
     "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/fall/fall_1.png",
      "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/fall/fall_2.png",
       "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/fall/fall_3.png",
        "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/idle/idle_0.png",
         "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/idle/idle_1.png",
          "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/idle/idle_2.png",
           "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/idle/idle_3.png",
            "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/idle/idle_4.png",
             "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/jump/jump_0.png",
              "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/run/run_0.png",
               "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/run/run_1.png",
                "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/run/run_2.png",
                 "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/player/run/run_3.png",
                  "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/turret/idle/idle_0.png",
                   "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/entities/entity_animations.txt",
                    "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/particles/p/0.png",
                     "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/particles/p/1.png",
                      "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/particles/p/2.png",
                       "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/particles/p/3.png",
                        "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/particles/p/4.png",
                         "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/particles/p/.png",
                          "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/controls_1.png",
                           "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/controls_2.png",
                            "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/core.png",
                             "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/cursor.png",
                              "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/gun.png",
                               "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/shot_example.png",
                                "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/sketch.png",
                                 "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/tileset.png",
                                  "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/turret_barrel.png",
                                   "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/turret_example.png",
                                    "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/images/turret_shot.png",
                                     "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/levels/level_1.txt",
                                      "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/levels/level_2.txt",
                                       "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/levels/level_3.txt",
                                        "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/levels/level_4.txt",
                                         "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/levels/level_5.txt",
                                          "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/levels/level_6.txt",
                                           "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/levels/level_7.txt",
                                            "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/sfx/death.wav",
                                             "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/sfx/explorion.wav",
                                              "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/sfx/jump.wav",
                                               "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/sfx/point.wav",
                                                "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/sfx/shoot.wav",
                                                 "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/sfx/turret_shoot.wav",
                                                  "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/clip.py",
                                                   "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/engine.py",
                                                    "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/fps.py",
                                                     "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/music.wav",
                                                      "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/outline.py",
                                                       "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/text.py",
                                                        "/Users/alexanderlongfellow/Desktop/code/Aeroblaster/data/tileset_loader.py"]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
